-- MySQL Script generated by MySQL Workbench
-- 11/21/15 18:29:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MyBlog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MyBlog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MyBlog` DEFAULT CHARACTER SET utf8 ;
USE `MyBlog` ;

-- -----------------------------------------------------
-- Table `MyBlog`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyBlog`.`users` (
  `UserID` INT(3) NOT NULL,
  `dateCreated` DATETIME NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyBlog`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyBlog`.`post` (
  `PostID` INT(3) NOT NULL,
  `dateCreated` VARCHAR(45) NULL,
  `usersID` INT(3) NOT NULL,
  `title` VARCHAR(45) NULL,
  `body` TEXT NULL,
  PRIMARY KEY (`PostID`),
  INDEX `usersID_idx` (`usersID` ASC),
  INDEX `PostUsersID` (`PostID` ASC, `usersID` ASC),
  CONSTRAINT `usersID`
    FOREIGN KEY (`usersID`)
    REFERENCES `MyBlog`.`users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyBlog`.`PostComments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyBlog`.`PostComments` (
  `PostCommentsID` INT NOT NULL AUTO_INCREMENT,
  `dateCreated` DATETIME NULL,
  `UserID` INT(3) NOT NULL,
  `PostID` INT(3) NOT NULL,
  `title` VARCHAR(45) NULL,
  `body` VARCHAR(255) NULL,
  PRIMARY KEY (`PostCommentsID`),
  INDEX `PostCommentsUserID` (`PostCommentsID` ASC, `UserID` ASC),
  INDEX `PostCommentsPostID` (`PostCommentsID` ASC, `PostID` ASC),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC),
  UNIQUE INDEX `PostID_UNIQUE` (`PostID` ASC),
  CONSTRAINT `UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `MyBlog`.`users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PostID`
    FOREIGN KEY (`PostID`)
    REFERENCES `MyBlog`.`post` (`PostID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
